version: '3.4'

services:
  dockerfile:
    image: dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

  react-app:
    image: react-app
    stdin_open: true
    ports: 
        - "3000-3000"

  mongo:
    image: 3.6.19-wanzhao/mongo3.4.20-xenial
    ports:
        - "27017:27017"
    networks: 
        - mern-app

