# Generated by Django 3.2.6 on 2021-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NV1', models.FloatField()),
                ('NV2', models.FloatField()),
                ('NV3', models.FloatField()),
            ],
        ),
    ]
