# Generated by Django 3.2.6 on 2021-10-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(unique=True)),
                ('nomeHospital', models.TextField(blank=True)),
                ('idsAvaliadores', models.TextField(blank=True)),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NV1', models.FloatField(default=7)),
                ('NV2', models.FloatField(default=8)),
                ('NV3', models.FloatField(default=9)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.TextField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('C', 'Conforme'), ('PC', 'Parcialmente Conforme'), ('NC', 'Nao Conforme'), ('NA', 'Nao Aplica')], default='NA', max_length=2)),
                ('pontuacao', models.FloatField(default=0)),
                ('comentario', models.TextField(blank=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.secao')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='configuracao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.configuracao'),
        ),
    ]
