# Generated by Django 3.2.6 on 2021-10-09 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField(blank=True, unique=True)),
                ('nomeHospital', models.TextField(blank=True)),
                ('idsAvaliadores', models.TextField(blank=True)),
                ('data', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.TextField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=2)),
                ('pontuacao', models.FloatField(blank=True, default=0)),
                ('comentario', models.TextField(blank=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.secao')),
            ],
        ),
    ]
