# Generated by Django 3.2.7 on 2021-10-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subtopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=2)),
                ('comentario', models.TextField(blank=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.secao')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_created=True)),
                ('codigo', models.TextField(blank=True)),
                ('nomeHospital', models.TextField(blank=True)),
                ('idsAvaliadores', models.TextField(blank=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Avaliacao.secao')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
