# Generated by Django 3.2.6 on 2021-09-01 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.TextField()),
                ('responsavel', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao', models.CharField(max_length=1)),
                ('indice', models.TextField()),
                ('qualificacao', models.TextField()),
                ('avaliacao_item', models.TextField()),
                ('rota', models.TextField()),
                ('comentario', models.TextField()),
                ('status', models.TextField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.avaliacao')),
            ],
        ),
    ]
