# Generated by Django 3.2.7 on 2021-09-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='comentario',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='comentarios',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='status',
            field=models.CharField(choices=[('D', 'Finalizado'), ('P', 'Pendente'), ('E', 'Erros')], max_length=2),
        ),
    ]
