# Generated by Django 3.2.7 on 2021-10-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='conforme',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='naoAplicavel',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='naoConforme',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subtopico',
            name='parcialConforme',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
