import { makeStyles } from '@material-ui/core'

export const useStyles = makeStyles((theme) => ({
  barraFundo: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: -1,
    backgroundColor: '#FFFEF2',
  },
  iconSpace: {
    position: 'absolute',
    right: '1vw',
    marginTop: '1.2vh',
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  iconPerfil: {
    maxHeight: '7vh',
  },
  barraTopo: {
    height: '10vh',
    width: '100%',
    backgroundColor: theme.palette.secondary.main,
    marginTop: '0vh',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  btnHome0: {
    backgroundColor: 'none',
    width: '10vw',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Open Sans',
  },
  btnHome1: {
    backgroundColor: 'none',
    width: '10vw',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Open Sans',
  },
  btnHome2: {
    backgroundColor: 'none',
    width: '10vw',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Open Sans',
  },
  btnHome3: {
    backgroundColor: 'none',
    width: '10vw',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    fontFamily: 'Open Sans',
    /*
        textDecoration: 'underline',
        textUnderlineOffset: '0.3vh',
        textDecorationColor: 'white',
        */
  },
  tituloBarraTopo: {
    color: 'white',
    textAlign: 'center',
    verticalAlign: 'middle',
    marginTop: '3vh',
  },
  imagem: {
    height: '15vh',
    [theme.breakpoints.down('md')]: {
      display: 'none',
    },
  },
  barraUm: {
    display: 'flex',
    padding: '0',
    margin: '0',
    height: '8vh',
    width: '100%',
    backgroundColor: '#FFFEF2',
  },
  barraDois: {
    padding: '0',
    margin: '0',
    height: '13vh',
    width: '100%',
    display: 'flex',
    backgroundColor: '#FFFEF2',
  },
  nomeTrab: {
    marginTop: '-2vh',
    marginLeft: 'auto',
    marginRight: 'auto',
    fontFamily: 'Open Sans',
    fontSize: '11.3vh',
    color: theme.palette.primary.main,
    textDecoration: 'underline',
    textDecorationThickness: '0.47vw',
    textUnderlineOffset: '0.3vh',
  },
  barraTres: {
    height: '40vh',
    width: '100vw',
    backgroundColor: '#FFFEF2',
  },
  caixaFlutuante: {
    height: '59vh',
    width: '85vw',
    backgroundColor: '#D6F0C8',
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: '1.5vh',
    borderWidth: '0.7vh',
    borderColor: theme.palette.primary.main,
    borderStyle: 'solid',
    display: 'flex',
    flexDirection: 'column',
  },
  tituloCaixa: {
    backgroundColor: '#D6F0C8',
    height: '4.5vw',
    width: '40vw',
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  tituloEntradaCodigo: {
    marginLeft: 'auto',
    marginRight: 'auto',
    marginTop: '2.5vh',
    fontSize: '3.5vh',
    color: theme.palette.secondary.main,
    fontFamily: 'Open Sans',
  },
  conteudoCaixa: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'green',
    width: 'auto',
    height: '50vh',
  },
  coluna1: {
    backgroundColor: '#D6F0C8',
    width: '20vw',
    height: '50vh',
    display: 'flex',
    flexDirection: 'column',
  },
  miniInput: {
    width: '11vw',
    height: '9vh',
    marginTop: '2.3vh',
    backgroundColor: theme.palette.secondary.main,
    textAlign: 'center',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderBottomLeftRadius: '2.1vh',
    borderBottomRightRadius: '2.1vh',
    display: 'flex',
    flexDirection: 'column',
  },
  miniInputAcima: {
    backgroundColor: theme.palette.secondary.main,
    width: 'auto',
    height: '4vh',
    display: 'flex',
  },
  titulo: {
    marginTop: '0vh',
    color: 'white',
    fontFamily: 'Open Sans',
    fontSize: '3vh',
    fontWeight: 'bold',
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  miniInputAbaixo: {
    backgroundColor: 'white',
    width: 'auto',
    height: '5vh',
    boxSizing: 'border-box',
    borderBottomLeftRadius: '1vh',
    borderBottomRightRadius: '1vh',
  },
  entrada: {
    height: '100%',
    width: '10vw',
    border: 'none',
    boxShadow: 'none',
    outline: 'none',
  },
  coluna2: {
    backgroundColor: '#D6F0C8',
    width: '65vw',
    height: '50vh',
  },
  plots: {
    marginLeft: '4vh',
    marginRight: 'auto',
    backgroundColor: 'none',
    width: '40vw',
    height: '47vh',
  },
  imgPlot: {
    width: 'auto',
    height: '47vh',
    marginLeft: '0vh',
  },
  btn: {
    padding: 0,
    margin: ' 0 auto',
    marginLeft: '53vw',
    marginRight: 'auto',
    marginTop: '1.5vh',
    height: '4vh',
    width: '10vw',
    backgroundColor: theme.palette.secondary.main,
    borderRadius: '1vh',
    border: 'none',
    verticalAlign: 'middle',
  },
  textoBtn: {
    textAlign: 'center',
    verticalAlign: 'middle',
    fontSize: '2vh',
    color: 'white',
    fontFamily: 'Open Sans',
    fontWeight: 'bold',
    marginTop: '0.5vh',
  },
  grafico: {},
}))
