# Generated by Django 3.2.6 on 2021-09-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infosPdf', models.CharField(max_length=1000)),
                ('cabecalhoPdf', models.CharField(max_length=100)),
                ('textoEntradaPdf', models.TextField()),
            ],
        ),
    ]
