# Generated by Django 3.2.6 on 2021-09-14 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geracaoPdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geracaopdf',
            name='cabecalhoPdf',
        ),
        migrations.RemoveField(
            model_name='geracaopdf',
            name='infosPdf',
        ),
        migrations.RemoveField(
            model_name='geracaopdf',
            name='textoEntradaPdf',
        ),
    ]
