# Generated by Django 3.2.6 on 2021-08-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('AvaliacaoId', models.AutoField(primary_key=True, serialize=False)),
                ('Analise', models.CharField(default='VALOR PADRÃO', max_length=500)),
                ('Hospital', models.CharField(default='VALOR PADRÃO', max_length=500)),
                ('Responsavel', models.CharField(default='VALOR PADRÃO', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('ChecklistId', models.AutoField(primary_key=True, serialize=False)),
                ('Secao', models.CharField(default='VALOR PADRÃO', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemId', models.AutoField(primary_key=True, serialize=False)),
                ('Qualificacao', models.CharField(default='VALOR PADRÃO', max_length=500)),
                ('Avaliacao', models.CharField(default='VALOR PADRÃO', max_length=500)),
                ('Nota', models.IntegerField(default='NULL')),
                ('Comentario', models.TextField(default='VALOR PADRÃO', max_length=1000)),
                ('Status', models.CharField(default='VALOR PADRÃO', max_length=500)),
            ],
        ),
    ]
