# Generated by Django 3.2.6 on 2021-09-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Secao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopico',
            name='nome',
            field=models.TextField(blank=True),
        ),
    ]
